# Generated by Django 6.0.1 on 2026-01-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='ativa',
            new_name='ativo',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='atualizada_em',
            new_name='atualizado_em',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='criada_em',
            new_name='criado_em',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
